# Generated by Django 3.0.7 on 2020-06-23 13:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название опции')),
                ('value', models.BooleanField(default=False, verbose_name='Выбрать опцию')),
            ],
        ),
        migrations.CreateModel(
            name='Push',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Заголовок уведомления')),
                ('text', models.CharField(blank=True, max_length=250, null=True, verbose_name='Текст уведомления')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('send_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата отправки')),
                ('is_sent', models.BooleanField(blank=True, default=False, verbose_name='Отправлен')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_pushes', to=settings.AUTH_USER_MODEL, verbose_name='Отправитель сообщения')),
            ],
            options={
                'ordering': ['-creation_date'],
                'permissions': (('can_mark_is_sent', 'Set push notification as sended'),),
            },
        ),
    ]
